### ISSUE TITLE
Azure service principal credentials not showing in GUI

### ISSUE THREAD

**Issue by kinihun** [kubecost/cost-analyzer#4]
Hi,

When I deploy Kubecost, I supply Azure Service Principal credentials and I can see then in the pricing-configs config-map but they don't show up in the web UI.
I couldn't find the Client-Secret under any resource.
Are they actually in use?

Best regards

**Comment by sylus** [comment]
I have this same problem ^_^

**Comment by AjayTripathy** [comment]
Hi @sylus sorry for the late response, but I wasn't able to reproduce this with the "serviceKeySecret". Could you clarify which set of secrets / credentials you're talking about? Is it the azureStorageAccount/azureStorageAccessKey/azureStorageContainer/azureStorageSecretName ?

**Comment by sylus** [comment]
Hey @AjayTripathy it was all of the azure billing settings not being visible in Kubecost which included the clientID and tenantID.

I attached an image and bug report in the zendesk issue: Number 332

**Comment by AjayTripathy** [comment]
Hi @sylus I took a look at that ticket. Looks like the following information is supplied:

```
  kubecostProductConfigs:

    azureBillingRegion: CA

    azureClientID: xxx

    azureClientPassword: xxxxx

    azureStorageAccessKey: xxxxx

    azureStorageAccount: xxx

    azureStorageContainer: xxx

    azureStorageCreateSecret: true

    azureSubscriptionID: xxx

    azureTenantID: xxx

```

Another config is needed: createServiceKeySecret: true. Was that set? The reason for this is that for full integration with Azure, 2 secrets are required. The one displayed in the UI is required to use the Price Metering API where we fetch price estimates from. The second is required to fetch data from the out-of-cluster costs and to get more accurate node pricing for spot instances/reservations/enterprise discounts.
